version: "3.3"
services:

  openskos-webserver:
    image: phpdockerio/nginx:latest
    container_name: openskos-webserver
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=openskos.local
    volumes:
      - .:/var/www/openskos
      - ./data/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - openskos-php-fpm

  openskos-php-fpm:
    build:
      context: ./
      dockerfile: ./data/docker/php-fpm/Dockerfile
    container_name: openskos-php-fpm
    network_mode: bridge
    volumes:
      - .:/var/www/openskos
      - ./data/docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - openskos-jena
      - openskos-solr
      - openskos-memcached
      - openskos-mysql

  openskos-jena:
    build: ./data/docker/jena-fuseki
    container_name: openskos-jena-fuseki
    network_mode: bridge
    ports:
     - "9001:3030"
    environment:
        ADMIN_PASSWORD : admin
    volumes:
      - ./data/fuseki/configuration:/fuseki/configuration
      - ./data/fuseki/databases:/fuseki/databases

  openskos-solr:
    build: ./data/docker/solr
    container_name: openskos-solr
    network_mode: bridge
    ports:
     - "9002:8983"
    volumes:
        - ./data/solr:/opt/solr/server/solr/openskos
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - openskos
      - /opt/solr/server/solr/openskos

  openskos-mysql:
    build: ./data/docker/mysql
    container_name: openskos-mysql
    network_mode: bridge
    ports:
     - "9003:3306"
    environment:
        MYSQL_ROOT_PASSWORD : secr3t
    volumes:
        - ./data/openskos-create.sql:/docker-entrypoint-initdb.d/openskos-create.sql

  openskos-memcached:
    image: 'bitnami/memcached:1'
    container_name: openskos-memcached
    network_mode: bridge
    ports:
      - "11211:11211"

  openskos-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: openskos-proxy
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "127.0.0.1:80:80"
