version: "3.3"
services:
  openskos-webserver:
    image: phpdockerio/nginx:latest
    container_name: openskos-webserver
    depends_on:
        - openskos-php-fpm
    volumes:
        - .:/var/www/openskos
        - ./data/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "9000:80"
    links:
     - openskos-php-fpm
  openskos-php-fpm:
    build: ./data/docker/php-fpm
    container_name: openskos-php-fpm
    volumes:
      - .:/var/www/openskos
      - ./data/docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
    links:
      - openskos-virtuoso
      - openskos-mysql
      - openskos-solr
  openskos-virtuoso:
    container_name: openskos-virtuoso
    image: tenforce/virtuoso
    environment:
      DBA_PASSWORD: secr3t
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://openskos.org/openskos"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:80"
  openskos-solr:
    build: ./data/docker/solr
    container_name: openskos-solr
    ports:
     - "9002:8983"
    volumes:
        - ./data/solr:/opt/solr/server/solr/openskos
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - openskos
      - /opt/solr/server/solr/openskos
  openskos-mysql:
    build: ./data/docker/mysql
    container_name: openskos-mysql
    ports:
     - "9003:3306"
    environment:
        MYSQL_ROOT_PASSWORD : secr3t
    volumes:
        - ./data/openskos-create.sql:/docker-entrypoint-initdb.d/openskos-create.sql
