version: "3.3"
services:
  openskos-webserver:
    image: phpdockerio/nginx:latest
    container_name: openskos-webserver
    volumes:
        - .:/var/www/openskos
        - ./data/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "9000:80"
  openskos-php-fpm:
    build:
      context: ./
      dockerfile: ./data/docker/php-fpm/Dockerfile
    container_name: openskos-php-fpm
    volumes:
      - .:/var/www/openskos
      - ./data/docker/php-fpm/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./data/docker/php-fpm/php-fpm.d:/etc/php7/php-fpm.d
      - ./data/docker/php-fpm/php-ini-overrides.ini:/etc/php7/conf.d/99-overrides.ini

  openskos-jena:
    build: ./data/docker/jena-fuseki
    container_name: openskos-jena-fuseki
    ports:
     - "9001:3030"
    networks:
      - default
      - openskos
    environment:
        ADMIN_PASSWORD : admin
    volumes:
      - ./data/fuseki/configuration:/fuseki/configuration
      - ./data/fuseki/databases:/fuseki/databases
  openskos-solr:
    build: ./data/docker/solr
    container_name: openskos-solr
    ports:
     - "9002:8983"
    volumes:
        - ./data/solr:/opt/solr/server/solr/openskos
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - openskos
      - /opt/solr/server/solr/openskos
    networks:
      - default
      - openskos
  openskos-mysql:
    build: ./data/docker/mysql
    container_name: openskos-mysql
    ports:
     - "9003:3306"
    environment:
        MYSQL_ROOT_PASSWORD : secr3t
    volumes:
        - ./data/openskos-create.sql:/docker-entrypoint-initdb.d/openskos-create.sql
    networks:
      - default
      - openskos
  openskos-memcached:
    image: bitnami/memcached:1
    container_name: openskos-memcached
    ports:
      - "11211:11211"

  openskos-proxy:
    image: jwilder/nginx-proxy
    container_name: openskos-proxy
    networks:
      - openskos
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "127.0.0.1:80:80"

  openskos-adminer:
    image: adminer
    container_name: openskos-adminer
    networks:
      - openskos
    environment:
      VIRTUAL_HOST: adminer.openskos.localhost
      ADMINER_DEFAULT_SERVER: openskos-mysql
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_DATABASE: openskos

networks:
  openskos:
    external:
      name: openskos
